services:
  app:
    build: .
    ports:
      - "8084:8084"
    env_file:
      - .env
    depends_on:
      - migrator
      - postgres
    restart: unless-stopped

  migrator:
    build: .
    command: ["./migrator"]
    env_file:
      - .env
    depends_on:
      - postgres
    restart: "no"

  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: simple_auth
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5434:5432"

volumes:
  postgres_data: