CREATE TABLE IF NOT EXISTS tokens
(
    id SERIAL PRIMARY KEY,
    guid TEXT NOT NULL UNIQUE,
    email TEXT NOT NULL UNIQUE,
    ip TEXT NOT NULL,
    hash BYTEA NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE INDEX IF NOT EXISTS idx_guid ON tokens (guid);